on:
  pull_request:
    types:
      - closed
    paths:
      - version

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Release
        run: |
          VERSION=$(cat version)
          gh release create "v$VERSION" --title "v$VERSION" --notes "Release v$VERSION" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
