---
name: pr-workflow-checks

on:
  pull_request:
    types:
      - opened

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  pre-merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check For Version Update
        id: pr-version-check
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          VERSION_UPDATED="$(git diff --name-only origin/${{ github.base_ref }}..HEAD -- 'version')"
          if [ -z $VERSION_UPDATED ]; then
            echo "Version file not updated"
            gh pr comment ${{ github.event.number }} --body "$PR_COMMENT_WARNING"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_COMMENT_WARNING: |
            Warning: This PR does not update the version file.

      - name: Check For Change Log Update
        id: pr-changelog-check
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          CHANGELOG_UPDATED="$(git diff --name-only origin/${{ github.base_ref }}..HEAD -- 'CHANGELOG.md')"
          if [ -z $CHANGELOG_UPDATED ]; then
            echo "Version file not updated"
            gh pr comment ${{ github.event.number }} --body "$PR_COMMENT_WARNING"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_COMMENT_WARNING: |
            Warning: This PR does not update the change log file.
