---
name: pr-workflow-merged

on:
  pull_request:
    types:
      - closed

jobs:
  on-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: PR Merged
        run: |
          echo "A PR was merged!"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR body: ${{ github.event.pull_request.body }}"
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "PR merged by: ${{ github.event.pull_request.merged_by.login }}"
          echo "PR merged at: ${{ github.event.pull_request.merged_at }}"
          echo "PR merged commit: ${{ github.event.pull_request.merge_commit_sha }}"
